[package]
name = "spinners-rs"
version = "1.0.0"
edition = "2021"
authors = ["jamesinaxx","François-Guillaume RIBREAU <github@fgribreau.com>"]
homepage = "https://github.com/jamesinaxx/spinners-rs"
repository = "https://github.com/jamesinaxx/spinners-rs"
readme = "README.md"
documentation = "https://docs.rs/spinners-rs"
description = "🛎 60+ Elegant terminal spinners for Rust"
keywords = ["spinner", "spin", "loader", "term", "terminal"]
categories = ["command-line-interface"]
license = "MIT"
include = ["src/**/*", "README.md"]


[package.metadata.release]
# cargo install cargo-release
# cargo release --dry-run
pre-release-commit-message = "Release {{version}} 🎉🎉"
pre-release-replacements = [ {file="README.md", search="Current release: [a-z0-9\\.-]+", replace="Current release: {{version}}"} , {file ="Cargo.toml", search="branch=\"[a-z0-9\\.-]+\"", replace="branch=\"{{version}}\""} ]


[dependencies]
lazy_static = "1.4"
maplit = "1.0"
