[package]
name = "spinners-rs"
version = "1.1.0"
edition = "2021"
authors = ["jamesinaxx","François-Guillaume RIBREAU <github@fgribreau.com>"]
homepage = "https://github.com/jamesinaxx/spinners-rs"
repository = "https://github.com/jamesinaxx/spinners-rs"
readme = "README.md"
documentation = "https://docs.rs/spinners-rs"
description = "🛎 60+ Elegant terminal spinners for Rust"
keywords = ["spinner", "spin", "loader", "term", "terminal"]
categories = ["command-line-interface"]
license = "MIT"
include = ["src/**/*", "README.md"]

[dependencies]
lazy_static = "1.4.0"
maplit = "1.0.2"
strum = "0.23.0"
strum_macros = "0.23.1"